// feature/doctor/doctorData.ts

import { Doctor } from "@/types";

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "D001",
    name: "Dr. Priya Sharma",
    age: 38,
    gender: "Female",
    specialty: "Cardiology",
    status: "Active",
    department: "Cardiology",
    phone: "+91 98765 11111",
    email: "priya.sharma@clinicsage.com",
    experience: 12,
    qualification: "MBBS, MD",
    patientsAssigned: 2,
    schedule: "Mon - Fri",
    joinedDate: "2018-06-01",
    lastActive: "2024-03-15",
  },
  {
    id: "D002",
    name: "Dr. Rahul Nair",
    age: 45,
    gender: "Male",
    specialty: "Endocrinology",
    status: "Active",
    department: "Endocrinology",
    phone: "+91 98765 22222",
    email: "rahul.nair@clinicsage.com",
    experience: 18,
    qualification: "MBBS, DM",
    patientsAssigned: 3,
    schedule: "Mon - Sat",
    joinedDate: "2015-03-10",
    lastActive: "2024-03-15",
  },
  {
    id: "D003",
    name: "Dr. Ananya Singh",
    age: 34,
    gender: "Female",
    specialty: "Surgery",
    status: "Active",
    department: "Surgery",
    phone: "+91 98765 33333",
    email: "ananya.singh@clinicsage.com",
    experience: 8,
    qualification: "MBBS, MS",
    patientsAssigned: 2,
    schedule: "Tue - Sat",
    joinedDate: "2020-01-15",
    lastActive: "2024-03-15",
  },
  {
    id: "D004",
    name: "Dr. Suresh Iyer",
    age: 52,
    gender: "Male",
    specialty: "Critical Care",
    status: "Active",
    department: "ICU",
    phone: "+91 98765 44444",
    email: "suresh.iyer@clinicsage.com",
    experience: 24,
    qualification: "MBBS, MD, EDIC",
    patientsAssigned: 4,
    schedule: "Mon - Fri",
    joinedDate: "2010-08-20",
    lastActive: "2024-03-15",
  },
  {
    id: "D005",
    name: "Dr. Meera Pillai",
    age: 41,
    gender: "Female",
    specialty: "Pulmonology",
    status: "Active",
    department: "Pulmonology",
    phone: "+91 98765 55555",
    email: "meera.pillai@clinicsage.com",
    experience: 15,
    qualification: "MBBS, MD, DNB",
    patientsAssigned: 3,
    schedule: "Mon - Fri",
    joinedDate: "2016-11-05",
    lastActive: "2024-03-15",
  },
  {
    id: "D006",
    name: "Dr. Karthik Menon",
    age: 36,
    gender: "Male",
    specialty: "Nephrology",
    status: "On Leave",
    department: "Nephrology",
    phone: "+91 98765 66666",
    email: "karthik.menon@clinicsage.com",
    experience: 9,
    qualification: "MBBS, DM",
    patientsAssigned: 0,
    schedule: "Wed - Sun",
    joinedDate: "2019-04-22",
    lastActive: "2024-03-10",
  },
  {
    id: "D007",
    name: "Dr. Divya Reddy",
    age: 29,
    gender: "Female",
    specialty: "Orthopedics",
    status: "Active",
    department: "Orthopedics",
    phone: "+91 98765 77777",
    email: "divya.reddy@clinicsage.com",
    experience: 4,
    qualification: "MBBS, MS",
    patientsAssigned: 1,
    schedule: "Mon - Sat",
    joinedDate: "2022-07-01",
    lastActive: "2024-03-15",
  },
  {
    id: "D008",
    name: "Dr. Arvind Joshi",
    age: 57,
    gender: "Male",
    specialty: "Neurology",
    status: "Inactive",
    department: "Neurology",
    phone: "+91 98765 88888",
    email: "arvind.joshi@clinicsage.com",
    experience: 28,
    qualification: "MBBS, MD, DM",
    patientsAssigned: 0,
    schedule: "Mon - Thu",
    joinedDate: "2008-02-14",
    lastActive: "2024-02-28",
  },
];
